### ISSUE TITLE
Throw warning when not using injection - Vue 2.5.2

### ISSUE THREAD

**Issue by AlexandreBonaventure** [egoist/styletron-vue#4]
According to documentation, it's not mandatory to use injection. However, it throws :
[Vue warn]: Injection "styletron" not found
[Vue warn]: Injection "theme" not found
(a bit annoying when you have plenty of styled components)

I could submit a PR to fix this easily by setting up default for injection (new 2.5.2 feature).

**Comment by egoist** [comment]
thanks, PR is definitely welcome :)
