### ISSUE TITLE
exposing specific props

### ISSUE THREAD

**Issue by AlexandreBonaventure** [egoist/styletron-vue#8]
see #7 (code is not battle test but it could work)
When styling a component eg : 
```js
const RouterLinkStyled = styled('router-link', props => css`
  opacity: ${props.active ? '1' : '0.5'};
  transition: opacity .2s ease-in-out;
`)
```
```pug
  router-link-styled(to="/example")
```

**Currently**
`to` props is not passed down to router link cause it's considered as an attribute.
**Proposed solution**
Add an option to expose props for the styled component so it's retro-compatible and doesn't introduce breaking change.

**Comment by egoist** [comment]
Should be fixed in latest version:

```js
styled('router-link', props => css`
  opacity: ${props.active ? '1' : '0.5'};
  transition: opacity .2s ease-in-out;
`, ['to', 'active'])
```

**Comment by AlexandreBonaventure** [comment]
Thanks, good job! I'll try new version very soon.
